variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test
  - build
  - pdf

.run_on_dockerhost: &run_on_dockerhost
  tags:
    - docker20
  before_script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
  image: gitlab.aimms.com:5050/other/dockerdev/documentation:latest

linkcheck:
  <<: *run_on_dockerhost
  stage: test
  script:
    - python3 -msphinx -W -b linkcheck . _build/linkcheck

build_and_install:
  <<: *run_on_dockerhost
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: always
    - when: never
  script:
    - python3 -msphinx -W -b html . _build/html
    - python3 -msphinx.ext.intersphinx _build/html/objects.inv > _build/html/help_index_functionreference.txt
    - bash load_ssh_key_for_deploy.sh
    - rsync -rt --delete-excluded _build/html/ support@data.aimms.com:/home/aimms/www/documentation.aimms.com/functionreference

compile_PDF:
  <<: *run_on_dockerhost
  stage: pdf
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: always
    - when: never
  script:
    - python3 -msphinx -M latex . _build
    - python3 -msphinx -M latexpdf . _build
    - bash load_ssh_key_for_deploy.sh
    - rsync -rt _build/latex/AIMMS_func.pdf support@data.aimms.com:/home/aimms/www/documentation.aimms.com/functionreference
    - rsync -rt _build/latex/AIMMS_func.pdf support@data.aimms.com:/home/aimms/www/data/download/manuals
  allow_failure: true
