variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test
  - build
  - pdf

.run_on_dockerhost: &run_on_dockerhost
  tags:
    - docker20
  image: "${DOCKER_ACCESS_URL}/other/dockerdev/documentation:latest"

linkcheck:
  <<: *run_on_dockerhost
  stage: test
  script:
    - python3 -msphinx -W -b linkcheck . _build/linkcheck

build_and_staging:
  <<: *run_on_dockerhost
  stage: build
  rules:
    - if: $CI_COMMIT_TAG       # no pipelines on tags
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'  #when a merge request is active, all pushes trigger two pipelines if we allow this one
      when: never
    - if: '$CI_COMMIT_BRANCH != "master"'
      when: always
    - when: never
  script:
    - sphinx-build -M html . _build
    - bash load_ssh_key_for_deploy.sh
    - ssh support@data.aimms.com mkdir -p /home/aimms/www/functional-reference-staging/${CI_COMMIT_BRANCH}
    - rsync -r --omit-dir-times --delete-excluded _build/html/ support@data.aimms.com:/home/aimms/www/functional-reference-staging/${CI_COMMIT_BRANCH}

build_and_install:
  <<: *run_on_dockerhost
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: always
    - when: never
  script:
    - python3 -msphinx -W -b html . _build/html
    - python3 -msphinx.ext.intersphinx _build/html/objects.inv > _build/html/help_index_functionreference.txt
    - cp -r _build/html functionreference
    - az storage copy -s 'functionreference' --recursive --destination-container '$web' -- --overwrite=true --as-subdir=true
    - bash load_ssh_key_for_deploy.sh
    - rsync -rt --delete-excluded _build/html/ support@data.aimms.com:/home/aimms/www/documentation.aimms.com/functionreference

compile_PDF:
  <<: *run_on_dockerhost
  stage: pdf
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: always
    - when: never
  script:
    - python3 -msphinx -M latex . _build
    - python3 -msphinx -M latexpdf . _build
    - mkdir -p functionreference && cp _build/latex/AIMMS_func.pdf functionreference/AIMMS_func.pdf
    - az storage copy -s 'functionreference' --recursive --destination-container '$web' -- --overwrite=true --as-subdir=true
    - bash load_ssh_key_for_deploy.sh
    - rsync -rt _build/latex/AIMMS_func.pdf support@data.aimms.com:/home/aimms/www/documentation.aimms.com/functionreference
    - rsync -rt _build/latex/AIMMS_func.pdf support@data.aimms.com:/home/aimms/www/data/download/manuals
  allow_failure: true
